// Fill out your copyright notice in the Description page of Project Settings.

#pragma once
#include "NativeGameplayTags.h"


namespace PlatformTags
{
	GAMELOCALSETTINGS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TRAIT_INPUT_SUPPORTS_GAMEPAD);
	GAMELOCALSETTINGS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TRAIT_INPUT_SUPPORTS_TRIGGER_HAPTICS);
	GAMELOCALSETTINGS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TRAIT_SUPPORTS_CHANGING_AUDIO_OUTPUT_DEVICE);
	GAMELOCALSETTINGS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TRAIT_SUPPORTS_BACKGROUND_AUDIO);
	GAMELOCALSETTINGS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TRAIT_SUPPORTS_WINDOWED_MODE);
	GAMELOCALSETTINGS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TRAIT_NEEDS_BRIGHTNESS_ADJUSTMENT);
}

namespace GameSettingsTags
{
	GAMELOCALSETTINGS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ACTION_EDIT_SAFEZONE);
	GAMELOCALSETTINGS_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ACTION_EDIT_BRIGHTNESS);
}
