// Fill out your copyright notice in the Description page of Project Settings.

#pragma once
#include "NativeGameplayTags.h"

namespace InitStateTags
{
	CUSTOMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SPAWNED);
	CUSTOMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DATA_AVAILABLE);
	CUSTOMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(DATA_INITIALIZED);
	CUSTOMCORE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GAMEPLAY_READY);
}